#include "grammar.h"
#include <stdio.h>

void print_nonterminal(char id){
	if(id == 0){printf("E");return;}
	if(id == -1){printf("Ep");return;}
	if(id == -2){printf("E1");return;}
	if(id == -3){printf("E2p");return;}
	if(id == -4){printf("E3");return;}
	if(id == -5){printf("E3p");return;}
	if(id == -6){printf("T");return;}
	if(id == -7){printf("Tp");return;}
	if(id == -8){printf("T2");return;}
	if(id == -9){printf("T3");return;}
	if(id == -10){printf("T4");return;}
	if(id == -11){printf("X");return;}
	if(id == -12){printf("Xp");return;}
	if(id == -13){printf("P");return;}
	if(id == -14){printf("F");return;}
	if(id == -15){printf("TT");return;}
	if(id == -16){printf("AfterThisInExp");return;}
	if(id == -17){printf("RestThisInExp");return;}
	if(id == -18){printf("AfterNew");return;}
	if(id == -19){printf("AfterNewId");return;}
	if(id == -20){printf("FilledBrackets");return;}
	if(id == -21){printf("R");return;}
	if(id == -22){printf("El");return;}
	if(id == -23){printf("Elp");return;}
	if(id == -24){printf("Relop");return;}
	if(id == -25){printf("Boolop");return;}
	if(id == -26){printf("Addop");return;}
	if(id == -27){printf("Multop");return;}
	if(id == -28){printf("Unop");return;}
	if(id == -29){printf("E2");return;}
	if(id == -30){printf("E1p");return;}
	if(id == -31){printf("Goal");return;}
	if(id == -32){printf("MainClass");return;}
	if(id == -33){printf("Blockstatements");return;}
	if(id == -34){printf("Blockstatement");return;}
	if(id == -35){printf("AfterId");return;}
	if(id == -36){printf("Eq");return;}
	if(id == -37){printf("NonclassVarDec");return;}
	if(id == -38){printf("Type1");return;}
	if(id == -40){printf("NonclassType");return;}
	if(id == -41){printf("Type");return;}
	if(id == -42){printf("Stmt");return;}
	if(id == -43){printf("StmtWithoutId");return;}
	if(id == -44){printf("OptElse");return;}
	if(id == -45){printf("OptExp");return;}
	if(id == -46){printf("AfterThisInStmt");return;}
	if(id == -47){printf("OptAfterIdExceptId");return;}
	if(id == -48){printf("AfterIdExceptId");return;}
	if(id == -49){printf("Dot");return;}
	if(id == -50){printf("DotR");return;}
	if(id == -51){printf("Bracket");return;}
	if(id == -52){printf("BracketR");return;}
	if(id == -53){printf("BracketEmpty");return;}
	if(id == -54){printf("ClassDeclarations");return;}
	if(id == -55){printf("ClassDeclaration");return;}
	if(id == -56){printf("Extends");return;}
	if(id == -57){printf("ClassBody");return;}
	if(id == -58){printf("ClassContent");return;}
	if(id == -59){printf("ClassComponent");return;}
	if(id == -60){printf("RestDec");return;}
	if(id == -61){printf("ParamsOpt");return;}
	if(id == -62){printf("Params");return;}
	if(id == -63){printf("ParamsRest");return;}
	if(id == -64){printf("Param");return;}

}